### ISSUE TITLE
x64 centos/debian cause window.Asc.asc_docs_api is not a constructor

### ISSUE THREAD

**Issue by Jane-lucky** [ONLYOFFICE/DocumentBuilder#47]
I have successfully compiled OnlyOffice, but when I launch the interface, an error will appear,：
![image](https://user-images.githubusercontent.com/33993053/102458927-e7dd5b00-407f-11eb-9645-df720259b7ab.png)

but this will not affect the start of the service. Then when I visited the interface, I couldn't access it；
The log is :
![image](https://user-images.githubusercontent.com/33993053/102458971-f461b380-407f-11eb-87c6-0119732ca66c.png)
I don't where is wrong,can't  to find problems.
Please help me.Thank you so much .

**Comment by ShockwaveNN** [comment]
1. Are you sure this is bug on DocumentBuilder?
   That is your plan to compile was? DocumentServer?

2. api errors is not good, how did you compile it, on which system and how
3. `Cannot Get /` error is correct, since compiled version didn't contain any Document Managements System, you should install it 
   yourself from https://github.com/ONLYOFFICE/document-server-integration
  nodejs is most advanced version

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
